apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: lib-ssdr-jenkins
    repository: jx3-kubernetes-vault
  - key: staging
  - key: production
  ingress:
    domain: jenkinsx.sandbox.lib.umd.edu
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: lib-ssdr-jenkins
  repository: bucketrepo
  secretStorage: vault
  vault: {}
  webhook: lighthouse
