filepath: ""
namespace: jx-vault
repositories:
- name: banzaicloud-stable
  url: https://kubernetes-charts.banzaicloud.com
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
releases:
- chart: banzaicloud-stable/vault-operator
  name: vault-operator
  version: 1.19.0
  forceNamespace: ""
  disableValidation: true
  skipDeps: null
- chart: jx3/vault-instance
  name: vault-instance
  version: 1.0.27
  forceNamespace: ""
  skipDeps: null
templates: {}
missingFileHandler: ""
renderedvalues: {}